### ISSUE TITLE
The NDCG metric

### ISSUE THREAD

**Issue by AaronHeee** [LaceyChen17/neural-collaborative-filtering#2]
The ndcg metric here is defined as 1/log2(rank_i) according to Xiangnan He's paper. Therefore, the formula in metrics.py should be log(2)/log(x+1) instead of log(2)/log(x+2) because the rank here starts from 1. Please update your code, thanks!

**Comment by AaronHeee** [comment]
typo: defined as 1/log2(rank_i+1) ⬆️

**Comment by LaceyChen17** [comment]
Thank you so much for pointing out this bug. I'll fix it asap.

**Comment by AaronHeee** [comment]
Thanks very much!
