### ISSUE TITLE
question about the version of pytorch

### ISSUE THREAD

**Issue by zhiqiangzhongddu** [LaceyChen17/neural-collaborative-filtering#5]
Hi,

Thanks for your kind sharing. 
I want to reproduce your results on my device, but my training results are too bad, 
The evaluating HR and NDCG of some epochs are 0.0000, do you have any idea about this case? And could you tell me the Pytorch version that you use in your side?

Thanks.

**Comment by LaceyChen17** [comment]
Could you share your training curve? I tested the repo using pytorch 0.2 but I guess it should work under 0.3 and 0.4 as well.

**Comment by GabbyHE** [comment]
> Hi,
> 
> Thanks for your kind sharing.
> I want to reproduce your results on my device, but my training results are too bad,
> The evaluating HR and NDCG of some epochs are 0.0000, do you have any idea about this case? And could you tell me the Pytorch version that you use in your side?
> 
> Thanks.


@LaceyChen17 @zhiqiangzhongddu , I got the same issue, see the curves ![image](https://user-images.githubusercontent.com/33002687/54662304-8e49a480-4b18-11e9-88f3-968b78489b23.png)on dataset ml-1m,

**Comment by zhiqiangzhongddu** [comment]
> Could you share your training curve? I tested the repo using pytorch 0.2 but I guess it should work under 0.3 and 0.4 as well.

**Comment by zhiqiangzhongddu** [comment]
> Could you share your training curve? I tested the repo using pytorch 0.2 but I guess it should work under 0.3 and 0.4 as well.

Before, I used Pytorch 1.0.1, the latest version. 
I tried Pytorch 0.4.0 with Cuda 80&90, but they don't work. 
Error:
RuntimeError: input and target shapes do not match: input [1024 x 1], target [1024]. 

And I'm not success to install Pytorch 0.2 and 0.3 on my computer. It seems Conda doesn't support them anymore.

**Comment by LaceyChen17** [comment]
I reproduced the bug in pytorch 1.0 as well. I am working on it now.

Yihong

________________________________
发件人: Zhiqiang ZHONG <notifications@github.com>
发送时间: 星期三, 三月 20, 2019 4:51 下午
收件人: LaceyChen17/neural-collaborative-filtering
抄送: Yihong Chen; Mention
主题: Re: [LaceyChen17/neural-collaborative-filtering] question about the version of pytorch (#5)


Could you share your training curve? I tested the repo using pytorch 0.2 but I guess it should work under 0.3 and 0.4 as well.

Before, I used Pytorch 1.0.1, the latest version.
I tried Pytorch 0.4.0 with Cuda 80&90, but they don't work.
Error:
RuntimeError: input and target shapes do not match: input [1024 x 1], target [1024].

And I'm not success to install Pytorch 0.2 and 0.3 on my computer. It seems Conda doesn't support them anymore.

―

**Comment by zhiqiangzhongddu** [comment]
news: the same bug exists with Pytorch-0.3.1, Cuda=90&80&100 in my computer.

**Comment by LaceyChen17** [comment]
@zhiqiangzhongddu @GabbyHE The bug was mainly caused by `MSELoss`. The repo works well under the latest pytorch(1.0.1post2) now. Thank you for reporting the bug. Also, pay attention to `l2_regularization` parameter. Strong  `l2_regularization` might lead to model underfitting and thus HR 0 & NDCG 0.

**Comment by GabbyHE** [comment]
> @zhiqiangzhongddu @GabbyHE
> 
> The bug was mainly caused by `MSELoss`.
> 
> The repo works well under the latest pytorch(1.0.1post2) now.
> 
> Thank you for reporting the bug. Also, pay attention to `l2_regularization` parameter.
> 
> Strong `l2_regularization` might lead to model underfitting and thus HR 0 & NDCG 0.

Thanks so much for fixing this bug.

**Comment by zhiqiangzhongddu** [comment]
> @zhiqiangzhongddu @GabbyHE
> 
> The bug was mainly caused by `MSELoss`.
> 
> The repo works well under the latest pytorch(1.0.1post2) now.
> 
> Thank you for reporting the bug. Also, pay attention to `l2_regularization` parameter.
> 
> Strong `l2_regularization` might lead to model underfitting and thus HR 0 & NDCG 0.
Thanks.
