### ISSUE TITLE
0 NDCG and HR for training NeuMF and GMF

### ISSUE THREAD

**Issue by ltz0120** [LaceyChen17/neural-collaborative-filtering#6]
Hi, I got a problem in training NeuMF and GMF. I always got 0 NDCG and HR value, and I didn't change anything on the code. The MLP is Okay though.

**Comment by LaceyChen17** [comment]
Did you check the l2 regularization parameter？

Yihong

________________________________
发件人: ltz0120 <notifications@github.com>
发送时间: 星期六, 三月 23, 2019 9:17 下午
收件人: LaceyChen17/neural-collaborative-filtering
抄送: Subscribed
主题: [LaceyChen17/neural-collaborative-filtering] 0 NDCG and HR for training NeuMF and GMF (#6)


Hi, I got a problem in training NeuMF and GMF. I always got 0 NDCG and HR value, and I didn't change anything on the code. The MLP is Okay though.

―

**Comment by ltz0120** [comment]
I changed the L2 regularization to 0 and it works. Thank you.

Tianze
